### ISSUE TITLE
Conflict with other "sendy" plugins

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-sendy#3]
Debugging a users website and it seems there is a conflict with another plugin Connects - Sendy Addon

From what i can tell both plugins use the same `SendyPHP` class name but the Connects plugin one is loaded first i assume since the error thrown is : 
````
[19-Nov-2018 10:19:06 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method SendyPHP::subscribe() in D:\MAMP\htdocs\edd\wp-content\plugins\edd-sendy\includes\class-edd-sendy.php:164
Stack trace:
#0 D:\MAMP\htdocs\edd\wp-content\plugins\edd-free-downloads\includes\actions.php(100): EDD_Sendy->subscribe_email(Array)
#1 D:\MAMP\htdocs\edd\wp-includes\class-wp-hook.php(288): edd_free_downloads_remove_optin(312)
#2 D:\MAMP\htdocs\edd\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 D:\MAMP\htdocs\edd\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#4 D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\payments\class-edd-payment.php(1748): do_action('edd_update_paym...', 312, 'publish', 'pending')
#5 D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\payments\class-edd-payment.php(859): EDD_Payment->update_status('publish')
#6 D:\MAMP\htdocs\edd\wp-content\plugins\edd-free-downloads\includes\download-actions.php(221): EDD_Payment->save()
#7 D:\MAMP\htdocs\edd\wp-includes\class-wp-ho in D:\MAMP\htdocs\edd\wp-content\plugins\edd-sendy\includes\class-edd-sendy.php on line 164
````

Their class does not have the `subscribe` method and uses different naming for methods.
Not an expert at this but i`m wondering if maybe we can "rename" our class to `EDD_SendyPHP`

Customer ticket: https://secure.helpscout.net/conversation/710317956/94370?folderId=2048992

**Comment by pippinsplugins** [comment]
Renaming it to `EDD_SendPHP` is a fine solution that should take care of the conflict.
